language: generic
sudo: required
services:
  - docker

before install:
  - docker build -t neillearns/appsecflaskapp -f Dockerfile .

script:

after_success:
  - docker build -t neillearns/appsecflaskapp -f Dockerfile .
  # Docker login using environmental variables
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push neillearns/appsecflaskapp
